//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    skeletons: [
      { bowAndArrow: 'bowAndArrow 1', id: 50 },
      { bowAndArrow: 'bowAndArrow 2', id: 26 },
      { bowAndArrow: 'bowAndArrow 3', id: 82 },
      { bowAndArrow: 'bowAndArrow 4', id: 37 },
      { bowAndArrow: 'bowAndArrow 5', id: 81 },
    ],
    dragons: [
      { shootFireAndSlash: 'shootFireAndSlash 1', id: 56 },
      { shootFireAndSlash: 'shootFireAndSlash 2', id: 19 },
      { shootFireAndSlash: 'shootFireAndSlash 3', id: 91 },
      { shootFireAndSlash: 'shootFireAndSlash 4', id: 81 },
      { shootFireAndSlash: 'shootFireAndSlash 5', id: 32 },
    ],
    cyclops: [
      { bigHammer: 'bigHammer 1', id: 70 },
      { bigHammer: 'bigHammer 2', id: 84 },
      { bigHammer: 'bigHammer 3', id: 42 },
      { bigHammer: 'bigHammer 4', id: 56 },
      { bigHammer: 'bigHammer 5', id: 65 },
    ],
  },
};
export default data;
